### ISSUE TITLE
ExchGwQuoine needs some adjustment

### ISSUE THREAD

**Issue by vsov** [gavincyi/BitcoinExchangeFH#22]
It seems that Quoine has quite a restrictive policy for anonymous querying, 4s interval is definitely too short and almost all queries fail with

`HTTP Error 429: Too Many Requests`

**Comment by gavincyi** [comment]
This issue has been a headache to me. Although in their official [website](https://developers.quoine.com/#rate-limiting) it mentions

"API users should not make more than 300 requests per 5 minute. Requests go beyond the limit will return with a 429 status"

but it looks like the actual rate is lower than that.

Any actual experience of how many requests the user can send?

**Comment by vsov** [comment]
I suppose, 300req/5min is only allowed for registered users with valid API key...

**Comment by gavincyi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ExchGwQuoine needs some adjustment](https://trello.com/c/P7jK47SP/3-exchgwquoine-needs-some-adjustment)

**Comment by gavincyi** [comment]
I inquired the exchange and they replied with valid timeframe the application exceeded the usage limit. Now, the issue has been resolved. Please upgrade to the latest version.
