### ISSUE TITLE
Bitstamp instrument

### ISSUE THREAD

**Issue by jpspfaria** [gavincyi/BitcoinExchangeFH#24]
Hi @gavincyi , is there a problem getting data from Bitstamp?

The print is stating that the connection is open but there is no instrument

2017-03-02 04:32:21,151 - INFO 
[ExchGwApiBitstamp]
Socket <Bitstamp> is opened.

2017-03-02 04:32:21,151 - INFO 
[ExchGwBitstamp]
Instrument "" is subscribed in channel Bitstamp

Thanks

**Comment by gavincyi** [comment]
[Bitstamp-BTCUSD-Ws]
exchange = Bitstamp
instmt_name = BTCUSD
instmt_code = ""
enabled = 1

The instrument code is used there so the instrument "BTCUSD" was successfully subscribed.

I think it should be displayed in a nicer way with instrument name instead. I'll resolve it soon.

**Comment by gavincyi** [comment]
Thanks for spotting out! 

The issue has been identified and will resolved soon.

**Comment by gavincyi** [comment]
The issue has been resolve and you can upgrade the current one

```
pip install --upgrade bitcoinexchangefh
```

**Comment by jpspfaria** [comment]
Hi @gavincyi, how are you doing?

I just updated your code on my server and the problem related to Bitstamp is occurring again.

I got the same problem of empty tables on:
exch_quoine_btcusd_trades
exch_quoine_btchkd_trades
exch_gatecoin_btchkd_trades
exch_bitstamp_btcusd_book
exch_bitstamp_btcusd_trades
exch_btcc_future_xbtcny_trades

**Comment by gavincyi** [comment]
Hi @jpspfaria, happy to see you again. :)

May I know which version you have installed? The latest version is all the order book and trade updates have been aggregated into a single table exch_<exchange name>_<instmt_name>_snapshot. The tables with suffix "trades" and "book" are no longer in use.
