### ISSUE TITLE
APIs authentication

### ISSUE THREAD

**Issue by jpspfaria** [gavincyi/BitcoinExchangeFH#25]
Hi @gavincyi , how can i configure each exchange API to use custom authentication credentials?

**Comment by gavincyi** [comment]
Currently the public market data does not require authentication credentials.

May I know which exchange you are referring to?

**Comment by zdavatz** [comment]
How can I authenticate with bitfinex? I would like to export my historical data to a CSV file.

**Comment by gavincyi** [comment]
Currently the public channel (book, ticker, trades) does not require authentication in Bitfinex. So you do need to authenticate Binfinex in BitcoinExchangeFH.

You can run BitcoinExchangeFH in CSV mode. (bitcoinexchangefh -csv -dbdir data/)

**Comment by zdavatz** [comment]
yes, but I would like to export my historical data of my accounts to a csv ;) and I guess that will need authentication.

**Comment by gavincyi** [comment]
I see. Sorry that currently the project does not support individual account information.

**Comment by zdavatz** [comment]
See this if you want to know more about where I want to go: 
https://github.com/ShaunHoyes/Bitfinex-account-monitor/issues/1#issuecomment-284280244

**Comment by gavincyi** [comment]
I think this functionality may go into my another [project](https://github.com/gavincyi/Bitzkrieg) which works on the trading system. I will consider your suggestion. Thanks!

**Comment by zdavatz** [comment]
Sure! What is your other project? Is that on github as well?

**Comment by gavincyi** [comment]
Yes please refer to the referenced issued.
