### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Shreyanshupare** [gavincyi/BitcoinExchangeFH#27]
can we connect to the azure data lake ?

**Comment by gavincyi** [comment]
I do not have much knowledge of Azure data lake. What API does it use?

**Comment by Shreyanshupare** [comment]
no api will use. such as  mysql db i want to store directly on Azure data lake store.

**Comment by gavincyi** [comment]
I haven't tried it before but therotically if you pass in the correct host address of the mysql database it will work properly.

Always welcome to report any issues if you find any error in the process.

**Comment by Shreyanshupare** [comment]
one more doubt i  have.. that when we stored data into csv form so table was created but the data is null ..why?

**Comment by Shreyanshupare** [comment]
please help me to store the data into csv form

**Comment by gavincyi** [comment]
Sorry for replying late. Do you mean the flag "-csv" does not work now?

**Comment by Shreyanshupare** [comment]
yes, table was created but data is null.please check . thanks

**Comment by gavincyi** [comment]
The issue has been resolved. Please upgrade it by

```
pip3 install --upgrade bitcoinexchangefh
```

You will see the application is updated to BitcoinExchangeFH-0.1.1rc5
